export const GET_NOTES_GROUPS_REQUEST = 'notesGroups/GET_NOTES_GROUPS_REQUEST';
export const GET_NOTES_GROUPS_SUCCESS = 'notesGroups/GET_NOTES_GROUPS_SUCCESS';
export const GET_NOTES_GROUPS_ERROR = 'notesGroups/GET_NOTES_GROUPS_ERROR';

export const CREATE_NOTES_GROUP_REQUEST = 'notesGroups/CREATE_NOTES_GROUP_REQUEST';
export const CREATE_NOTES_GROUP_SUCCESS = 'notesGroups/CREATE_NOTES_GROUP_SUCCESS';
export const CREATE_NOTES_GROUP_ERROR = 'notesGroups/CREATE_NOTES_GROUP_ERROR';

export const DELETE_NOTES_GROUP_REQUEST = 'notesGroups/DELETE_NOTES_GROUP_REQUEST';
export const DELETE_NOTES_GROUP_SUCCESS = 'notesGroups/DELETE_NOTES_GROUP_SUCCESS';
export const DELETE_NOTES_GROUP_ERROR = 'notesGroups/DELETE_NOTES_GROUP_ERROR';
