export const CREATE_NOTE_REQUEST = 'note/CREATE_NOTE_REQUEST';
export const CREATE_NOTE_SUCCESS = 'note/CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_ERROR = 'note/CREATE_NOTE_ERROR';

export const FETCH_NOTE_REQUEST = 'note/FETCH_NOTE_REQUEST';
export const FETCH_NOTE_SUCCESS = 'note/FETCH_NOTE_SUCCESS';
export const FETCH_NOTE_ERROR = 'note/FETCH_NOTE_ERROR';

export const SAVE_NOTE_REQUEST = 'note/SAVE_NOTE_REQUEST';
export const SAVE_NOTE_SUCCESS = 'note/SAVE_NOTE_SUCCESS';
export const SAVE_NOTE_ERROR = 'note/SAVE_NOTE_ERROR';

export const DELETE_NOTE_REQUEST = 'note/DELETE_NOTE_REQUEST';
export const DELETE_NOTE_SUCCESS = 'note/DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_ERROR = 'note/DELETE_NOTE_ERROR';
